v1.0.0
GoRunMaxim/binaryTree pull request #1
Opened 2020-12-19 10:17 UTC by GoRunMaxim

Upload Tree struct and its constructor. 
Upload funcs: Same, Walk and tests for them.

2020-12-21 13:52 UTC, papahmsolo requested changes
This solution probably works fine for small trees. You can benchmark it now and then we'll compare it to a better solution. Hint: do we always need to walk over the whole trees to compare?  Or maybe we can sometimes tell trees are not equal in the middle of the walk?

2020-12-21 13:52 UTC, papahmsolo commented on tree.go
> +package tree
Package comment

2020-12-21 13:52 UTC, papahmsolo commented on tree.go
> +	}
Do we need `else` here?

2020-12-21 13:52 UTC, papahmsolo commented on tree.go
> +	sort.Ints(data2)
Why sorting slices?

2020-12-21 13:52 UTC, papahmsolo commented on tree.go
> +	}
What's the point in sending tree values to the channel if you can just append to a slice while walking the tree?

2020-12-21 14:15 UTC, GoRunMaxim commented on tree.go
> +	sort.Ints(data2)
Unnecessary work. Deleted

2020-12-21 14:21 UTC, GoRunMaxim commented on tree.go
> +	}
**Implement the Same function using Walk to determine whether t1 and t2 store the same values.**

Walk function reads tree values and send them to channel, then we read this values and append to slice. Don't we need to do this?

2020-12-21 14:24 UTC, GoRunMaxim commented on tree.go
> +	}
I suppose we do. Or what is the better way to insert the node?

2020-12-21 14:30 UTC, GoRunMaxim commented on tree.go
> +package tree
Fixed

2020-12-22 10:22 UTC, GoRunMaxim commented on tree.go
> +	}
Fixed

2020-12-23 08:39 UTC, papahmsolo requested changes
Looks very good!
I've made some suggestions to improve your code.

2020-12-23 08:39 UTC, papahmsolo commented on tree.go
> +	}
It always falls into the `else` category, so if you just delete `else` it wouldn't change anything

2020-12-23 08:39 UTC, papahmsolo commented on tree.go
> +}
That's a nice way to walk a tree of arbitrary length! I found your previous version with `Walk` and `Walker` a little simpler, to be honest, but this works just fine. Pick the one you like better.

2020-12-23 08:39 UTC, papahmsolo commented on tree_test.go
> +}
That is a nice test! As a suggestion, I'd return the number of actual nodes sent to the channel if it was closed earlier than expected

2020-12-23 08:39 UTC, papahmsolo commented on tree_test.go
> +		equal bool
I'd call them `nodes` rather than `data`

2020-12-23 08:39 UTC, papahmsolo commented on tree_test.go
> +		}
Try to fail this test deliberately, you'll find the error message does not provide many details about the problem. What about printing the contents of these trees?

2020-12-23 09:25 UTC, GoRunMaxim commented on tree.go
> +}
**It always falls into the else category, so if you just delete else it wouldn't change anything**

That doesn't work like this, we do need else statement. Try it by urself. 

**Pick the one you like better.**

Let's just leave only one long function.

2020-12-23 09:29 UTC, GoRunMaxim commented on tree_test.go
> +		equal bool
It's  actually not nodes by themselves, but the value that this nodes has. But I will change this.

2020-12-23 10:51 UTC, papahmsolo commented on tree.go
> +}
Oh, I see the problem, missed the `return` statement. I just do it this way

2020-12-23 11:21 UTC, papahmsolo requested changes
Almost there

2020-12-23 11:21 UTC, papahmsolo commented on tree_test.go
> +			}
You can specify in the error message what you expected and what you actually got

2020-12-23 13:50 UTC, papahmsolo requested changes
Well done!

2020-12-23 13:51 UTC, papahmsolo approved these changes
Well done!

2020-12-23 13:52 UTC, merged